[build]
  publish = "."
  command = "echo 'PHP uygulaması build edildi'"

[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200

[build.environment]
  PHP_VERSION = "8.1"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff" 